### ISSUE TITLE
Kotlin 2.0.20 breaks patcher in fork

### ISSUE THREAD

**Issue by scrayos** [PaperMC/paperweight#254]
I've added the kotlin(jvm) gradle plugin through api and server patches in my fork of Paper. This worked fine for every version I included so far, but did break now that I've bumped Kotlin to version 2.0.20 (from 2.0.0). This is the error message when I execute `./gradlew generateDevelopmentBundle`:

```
> Configure project :
paperweight-patcher v1.7.2 (running on 'Linux')

> Configure project :paper
paperweight-core v1.7.1 (running on 'Linux')

> Task :applyApiPatches
Creating cardboard-api from patch source...
Applying patches to cardboard-api...
7 patches applied cleanly to cardboard-api

> Task :applyPaperApiGeneratorPatches
Creating generated from patch source...
Applying patches to generated...
No patches found

> Task :applyServerPatches
Creating cardboard-server from patch source...
Importing 1 classes from vanilla...
Importing 0 data files from vanilla...
Importing 0 classes from library sources...
Applying patches to cardboard-server...
12 patches applied cleanly to cardboard-server

BUILD SUCCESSFUL in 9s
5 actionable tasks: 5 executed
scrayos@scrayospc ..rojects/JustChunks/Minecraft/Cardboard (git)-[main] % ./gradlew createMojmapPaperclipJar generateDevelopmentBundle

> Configure project :
paperweight-patcher v1.7.2 (running on 'Linux')

> Configure project :paper
paperweight-core v1.7.1 (running on 'Linux')

> Task :generateDevelopmentBundle
Using 'diff (GNU diffutils) 3.10'.

> Task :generateDevelopmentBundle FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateDevelopmentBundle'.
> Collection contains no element matching the predicate.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 1m 28s
24 actionable tasks: 16 executed, 5 from cache, 3 up-to-date
```

When I executed this with --stacktrace it was printing this stacktrace:

```
Caused by: java.util.NoSuchElementException: Collection contains no element matching the predicate.
        at io.papermc.paperweight.tasks.GenerateDevBundle.determineLibraries(GenerateDevBundle.kt:403)
        at io.papermc.paperweight.tasks.GenerateDevBundle.createBuildDataConfig(GenerateDevBundle.kt:279)
        at io.papermc.paperweight.tasks.GenerateDevBundle.createBundleConfig(GenerateDevBundle.kt:265)
        at io.papermc.paperweight.tasks.GenerateDevBundle.run(GenerateDevBundle.kt:145)
```

I'm using paperweight.patcher version 1.7.2 and use upstream commit https://github.com/PaperMC/Paper/commit/2fdb2e9dcdfb127cb99134f9bec60dcc2a6954d2 (latest).

**Comment by scrayos** [comment]
Sadly, this still does not work with paperweight v1.7.5 and Kotlin 2.0.21 (Gradle 8.10.2) and upstream commit https://github.com/PaperMC/Paper/commit/c28d89d625c60243c52857e0c7e6398b73602156.

**Comment by scrayos** [comment]
Still occurs as of paperweight 1.7.6 and Kotlin 2.1.0. - therefore it seems likely, that the underlying logic needs to be changed or that adjustments need to be made in the import/use of kotlin.

**Comment by scrayos** [comment]
I found a workaround:

In previous versions of `kotlin("jvm")`, the version of other kotlin libraries like `implementation(kotlin("reflect"))` could be omitted. But now, it has to be explicitly stated like this: `implementation(kotlin("reflect", "2.1.0"))`. This however, should still also work without the version (as it does in other setups).

**Comment by jpenilla** [comment]
This will be fixed in 2.0
