### ISSUE TITLE
In some exceptional cases I get NoClassDefFoundError error

### ISSUE THREAD

**Issue by Pledix** [PaperMC/paperweight#258]
If I named any interface as VersionWrapper (Maybe the same error occurs in classes too, I haven't tried it.)
or
In the abstract classes I created with any name in the main package
```
[14:07:03] [Server thread/INFO]: [ShopPlugin] Enabling ShopPlugin v1.0.0
[14:07:03] [Server thread/WARN]: [ShopPlugin] success
[14:07:03] [Server thread/ERROR]: Error occurred while enabling ShopPlugin v1.0.0 (Is it up to date?)
java.lang.NoClassDefFoundError: dev/pledix/shopplugin/Pricing
	at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:889) ~[?:?]
	at io.papermc.reflectionrewriter.runtime.DefineClassReflectionProxyImpl.defineClass(DefineClassReflectionProxyImpl.java:55) ~[reflection-rewriter-runtime-0.0.1.jar:?]
	at io.papermc.paper.pluginremap.reflect.PaperReflection.defineClass(PaperReflection.java:172) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.defineClass(Unknown Source) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at ShopPlugin-1.0.0.jar/dev.pledix.shopplugin.Main$CustomClassLoader.defineClass(Main.java:181) ~[ShopPlugin-1.0.0.jar:?]
	at ShopPlugin-1.0.0.jar/dev.pledix.shopplugin.Main.loadAndExecuteJarFromURL(Main.java:148) ~[ShopPlugin-1.0.0.jar:?]
	at ShopPlugin-1.0.0.jar/dev.pledix.shopplugin.Main.onEnable(Main.java:55) ~[ShopPlugin-1.0.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:632) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:581) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:717) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:464) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1218) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:350) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: dev.pledix.shopplugin.Pricing
	at java.base/java.lang.ClassLoader.findClass(ClassLoader.java:733) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	... 21 more
[14:07:03] [Server thread/INFO]: [Vendors] Disabling ShopPlugin v1.0.0
```

**Comment by electronicboy** [comment]
this is a tooling repo, not a place for bug reports with software, etc; (This is also generally not enough info to diagnose what is going on)
