### ISSUE TITLE
Paperweight-userdev setup fails in multi-module project with kotlinx.serialization plugin

### ISSUE THREAD

**Issue by NichtStudioCode** [PaperMC/paperweight#260]
The setup of the paperweight-userdev plugin fails with the following exception in multi-module projects, when one module uses the [kotlinx.serialization](https://github.com/Kotlin/kotlinx.serialization) plugin and another one doesn't (and both use paperweight-userdev). This does not happen when all modules use the plugin, as far as I can see kotlinx.serialization causes some sort of "class path isolation" between the different modules at build time.

```
Caused by: java.lang.ClassCastException: class io.papermc.paperweight.userdev.internal.setup.UserdevSetup$Inject cannot be cast to class io.papermc.paperweight.userdev.internal.setup.UserdevSetup (io.papermc.paperweight.userdev.internal.setup.UserdevSetup$Inject is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader$InstrumentingVisitableURLClassLoader @61ecac73; io.papermc.paperweight.userdev.internal.setup.UserdevSetup is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader$InstrumentingVisitableURLClassLoader @1d3c8c88)
	at io.papermc.paperweight.userdev.PaperweightUser.createSetup(PaperweightUser.kt:321)
	at io.papermc.paperweight.userdev.PaperweightUser.access$createSetup(PaperweightUser.kt:57)
	at io.papermc.paperweight.userdev.PaperweightUser$apply$userdevSetup$2.invoke(PaperweightUser.kt:87)
	at io.papermc.paperweight.userdev.PaperweightUser$apply$userdevSetup$2.invoke(PaperweightUser.kt:87)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at io.papermc.paperweight.userdev.PaperweightUser.apply$lambda$1(PaperweightUser.kt:87)
	at io.papermc.paperweight.userdev.PaperweightUser.access$apply$lambda$1(PaperweightUser.kt:57)
	at io.papermc.paperweight.userdev.PaperweightUser$apply$4.execute(PaperweightUser.kt:166)
	at io.papermc.paperweight.userdev.PaperweightUser$apply$4.execute(PaperweightUser.kt:134)
	at org.gradle.internal.code.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:123)
(... and more gradle-internal lines)
```

I have created a sample repository to reproduce this issue: [NichtStudioCode/paperweight-userdev-kotlinx-serialization-conflict](https://github.com/NichtStudioCode/paperweight-userdev-kotlinx-serialization-conflict).

**Comment by lynxplay** [comment]
Presumably just a duplicate of https://github.com/PaperMC/paperweight/issues/161 ?

**Comment by NichtStudioCode** [comment]
yep, my bad
