### ISSUE TITLE
1.1.7 causes exception for forks of forks

### ISSUE THREAD

**Issue by PaulBGD** [PaperMC/paperweight#49]
Reproduction:

1. Clone https://github.com/clrxbl/byof/
2. Set the version of paperweight to 1.1.8
3. Update tuinityRef to 05711635d69b64ee17dbbe9171887d1d45e54a4f
3. Run applyPatches

Result:
```
> Task :getTuinityUpstreamData FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':tuinity:applyServerPatches'.
> Failed to query the value of task ':tuinity:applyServerPatches' property 'sourceMcDevJar'.
   > fromJson(json, typeToken<T>()) must not be null
```

Stacktrace:
```
Caused by: java.lang.IllegalStateException: fromJson(json, typeToken<T>()) must not be null
        at io.papermc.paperweight.util.UpstreamDataKt.readUpstreamData(UpstreamData.kt:56)
        at io.papermc.paperweight.patcher.PaperweightPatcher$readUpstreamData$1$1$1.call(PaperweightPatcher.kt:148)
        at io.papermc.paperweight.patcher.PaperweightPatcher$readUpstreamData$1$1$1.call(PaperweightPatcher.kt:148)
        at org.gradle.api.internal.provider.DefaultProvider.calculateOwnValue(DefaultProvider.java:66)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:103)
        at org.gradle.api.internal.provider.FlatMapProvider.calculateOwnValue(FlatMapProvider.java:50)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:103)
        at org.gradle.api.internal.provider.FlatMapProvider.calculateOwnValue(FlatMapProvider.java:50)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:103)
        at org.gradle.api.internal.provider.TransformBackedProvider.calculateOwnValue(TransformBackedProvider.java:64)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:103)
        at org.gradle.api.internal.provider.TransformBackedProvider.calculateOwnValue(TransformBackedProvider.java:64)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:103)
        at org.gradle.api.internal.provider.MappingProvider.calculateOwnValue(MappingProvider.java:55)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:103)
        at org.gradle.api.internal.provider.DefaultProperty.calculateValueFrom(DefaultProperty.java:128)
        at org.gradle.api.internal.provider.DefaultProperty.calculateValueFrom(DefaultProperty.java:25)
        at org.gradle.api.internal.provider.AbstractProperty.doCalculateValue(AbstractProperty.java:133)
        ... 189 more
```

**Comment by DenWav** [comment]
I think I know what's causing this, thanks.

**Comment by PaulBGD** [comment]
The error persists on 1.1.8. I've added to the repro to modify the tuinityRef to show this.
